### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by QSZJAVA** [zzhougy/jianzhi-portal#1]
您好，我目前在做这个项目，遇到了一些问题，请问可以加个联系方式交流一下吗？

**Comment by zzhougy** [comment]
可以，加我微信907038364





------------------ 原始邮件 ------------------
发件人: QSZJAVA ***@***.***&gt;
发送时间: 2023年3月31日 19:35
收件人: zzhougy/jianzhi-portal ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[zzhougy/jianzhi-portal] 您好 (Issue #1)

**Comment by sunny-cgw** [comment]
> 您好，我目前在做这个项目，遇到了一些问题，请问可以加个联系方式交流一下吗？

你好，你解决问题了吗，可以交流一下吗

**Comment by QSZJAVA** [comment]
解决了 项目没啥bug
